[keymap]
gdl = "cd /home/imsohexy/Downloads"
gdc = "cd /home/imsohexy/Documents"
gp = "cd /home/imsohexy/Pictures"
gsc = "cd /home/imsohexy/Pictures/screenshots"
dd = "!rm -rfi %f"
pi = "!!clear; chafa -f kitty %"
