[keymap]
gdl = "cd ~/Downloads"
gdc = "cd ~/Documents"
gp = "cd ~/Pictures"
gsc = "cd ~/Pictures/screenshots"
dd = "!rm -rfi %f"
pi = "!!clear; chafa -f kitty %"
md = "cmdline-set !mkdir -p "
mf = "cmdline-set !touch "
